// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeNPwHpaRkG86CB50nzr8gqWFc-kQkYYw',
    appId: '1:15891111955:web:691bc7bc835f90175c1fe6',
    messagingSenderId: '15891111955',
    projectId: 'ev-go-373c1',
    authDomain: 'ev-go-373c1.firebaseapp.com',
    storageBucket: 'ev-go-373c1.firebasestorage.app',
    measurementId: 'G-BQBY2WRM24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMt4shAZBMIDVTNTP_INJ6LtOm8s_gCCM',
    appId: '1:15891111955:android:e6829548254568485c1fe6',
    messagingSenderId: '15891111955',
    projectId: 'ev-go-373c1',
    storageBucket: 'ev-go-373c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5tMjRFeqMJ-7hJcXevariHbIV33hTDbw',
    appId: '1:15891111955:ios:b8cae967173093cc5c1fe6',
    messagingSenderId: '15891111955',
    projectId: 'ev-go-373c1',
    storageBucket: 'ev-go-373c1.firebasestorage.app',
    iosBundleId: 'com.ev.ride.ev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5tMjRFeqMJ-7hJcXevariHbIV33hTDbw',
    appId: '1:15891111955:ios:b8cae967173093cc5c1fe6',
    messagingSenderId: '15891111955',
    projectId: 'ev-go-373c1',
    storageBucket: 'ev-go-373c1.firebasestorage.app',
    iosBundleId: 'com.ev.ride.ev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeNPwHpaRkG86CB50nzr8gqWFc-kQkYYw',
    appId: '1:15891111955:web:e102306362bd49645c1fe6',
    messagingSenderId: '15891111955',
    projectId: 'ev-go-373c1',
    authDomain: 'ev-go-373c1.firebaseapp.com',
    storageBucket: 'ev-go-373c1.firebasestorage.app',
    measurementId: 'G-74VH1DQVGS',
  );
}
