// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkByQALxi6tU9tj5Z9TKr4LPs5DJ_iQgw',
    appId: '1:826663543245:web:e3390b32b37318ec012484',
    messagingSenderId: '826663543245',
    projectId: 'cleancore-b98d6',
    authDomain: 'cleancore-b98d6.firebaseapp.com',
    storageBucket: 'cleancore-b98d6.firebasestorage.app',
    measurementId: 'G-RSDBCRG5KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIzj1m8x8-9mLV5xCf5NOH76EQeltLawk',
    appId: '1:826663543245:android:f735114824a2214e012484',
    messagingSenderId: '826663543245',
    projectId: 'cleancore-b98d6',
    storageBucket: 'cleancore-b98d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPTwTp1c63G1TS3qFGMzPRuwvLAJDN86k',
    appId: '1:826663543245:ios:3d223b14296e9756012484',
    messagingSenderId: '826663543245',
    projectId: 'cleancore-b98d6',
    storageBucket: 'cleancore-b98d6.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5tMjRFeqMJ-7hJcXevariHbIV33hTDbw',
    appId: '1:15891111955:ios:b8cae967173093cc5c1fe6',
    messagingSenderId: '15891111955',
    projectId: 'ev-go-373c1',
    storageBucket: 'ev-go-373c1.firebasestorage.app',
    iosBundleId: 'com.ev.ride.ev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeNPwHpaRkG86CB50nzr8gqWFc-kQkYYw',
    appId: '1:15891111955:web:e102306362bd49645c1fe6',
    messagingSenderId: '15891111955',
    projectId: 'ev-go-373c1',
    authDomain: 'ev-go-373c1.firebaseapp.com',
    storageBucket: 'ev-go-373c1.firebasestorage.app',
    measurementId: 'G-74VH1DQVGS',
  );
}